import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillMessage,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Antti Murtokangas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Antti murtokangas</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Antti Murtokangas
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Student & Hobbyist frontend coder
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Automation Engineering Student & Hobbyist Coder Passionate About React Web Development
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="mailto:antti.murtsi@gmail.com" target="_blank" rel="noopener noreferrer">
              <AiFillMail />
            </a>
            <a href="https://www.linkedin.com/in/antti-murtokangas-562725158/" target="_blank" rel="noopener noreferrer">
              <AiFillLinkedin />
            </a>
                <a href="https://github.com/Murtsi" target="_blank" rel="noopener noreferrer">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-gray-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            </div>
          </div>
        </section>
        <section>
          <div>
          <h3 className="text-5xl py-1 text-gray-900 dark:text-gray-100 font-bold">
              What I Can Offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              consulted for and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-light-blue-500 dark:bg-gray-700 flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-900 dark:text-gray-100">
                My skills
              </h3>
              <p className="py-2 text-gray-900 dark:text-gray-100">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-900 dark:text-gray-100 py-1">Photoshop</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Illustrator</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Figma</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-light-blue-500 dark:bg-gray-700 flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-900 dark:text-gray-100">
                My technical background
              </h3>
              <p className="py-2 text-gray-900 dark:text-gray-100">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-900 dark:text-gray-100 py-1">Photoshop</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Illustrator</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Figma</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-light-blue-500 dark:bg-gray-700 flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-900 dark:text-gray-100">
                My personal traits
              </h3>
              <p className="py-2 text-gray-900 dark:text-gray-100">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-900 dark:text-gray-100 py-1">Photoshop</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Illustrator</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Figma</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Indesign</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <div className="bg-white shadow-lg rounded-xl p-10 dark:bg-gray-800">
              <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Portofolio</h3>
              <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                Since the beginning of my journey as a freelance designer and
                developer, I've done remote work for
                <span className="text-teal-500"> agencies </span>
                consulted for <span className="text-teal-500">startups </span>
                and collaborated with talanted people to create digital products
                for both business and consumer use.
              </p>
              <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                I offer from a wide range of services, including brand design,
                programming and teaching.
              </p>
              <section className="py-10">
                <div className="bg-light-blue-500 shadow-lg rounded-xl p-10 dark:bg-gray-700">
                  <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Work Experience</h3>
                  <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                    I have worked on various projects as a freelance designer and developer, collaborating with talented people to create digital products for both business and consumer use.
                  </p>
                  <ul className="list-disc list-inside text-gray-900 dark:text-gray-100">
                    <li>Freelance Designer at XYZ Agency (2020 - Present)</li>
                    <li>Frontend Developer at ABC Startup (2018 - 2020)</li>
                    <li>Intern at DEF Corporation (2017 - 2018)</li>
                  </ul>
                </div>
                <div className="mt-10 bg-light-blue-500 shadow-lg rounded-xl p-10 dark:bg-gray-700">
                  <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Education</h3>
                  <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                    I have a strong educational background in both design and development.
                  </p>
                  <ul className="list-disc list-inside text-gray-900 dark:text-gray-100">
                    <li>Bachelor's Degree in Automation Engineering, University of Technology (2015 - 2019)</li>
                    <li>Certificate in Web Development, Online Course (2020)</li>
                  </ul>
                </div>
                <div className="mt-10 bg-light-blue-500 shadow-lg rounded-xl p-10 dark:bg-gray-700">
                  <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Language Skills</h3>
                  <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                    I am proficient in multiple languages, which allows me to work with a diverse range of clients.
                  </p>
                  <ul className="list-disc list-inside text-gray-900 dark:text-gray-100">
                    <li>English (Fluent)</li>
                    <li>Finnish (Native)</li>
                    <li>Swedish (Intermediate)</li>
                  </ul>
                </div>
              </section>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
