import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillMessage,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useInView } from 'react-intersection-observer';
import Modal from "react-modal"; // Import the modal library
import { Worker, Viewer } from '@react-pdf-viewer/core'; // Import react-pdf components
import '@react-pdf-viewer/core/lib/styles/index.css';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false); // State for modal

  const { ref: workRef, inView: workInView } = useInView();
  const { ref: educationRef, inView: educationInView } = useInView();
  const { ref: languageRef, inView: languageInView } = useInView();
  const { ref: offerRef, inView: offerInView } = useInView();
  const { ref: portfolioRef, inView: portfolioInView } = useInView();

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Antti Murtokangas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Antti murtokangas</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <button
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  onClick={() => setIsModalOpen(true)} // Open modal on click
                >
                  Resume
                </button>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Antti Murtokangas
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Student & Hobbyist frontend coder
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Automation Engineering Student & Hobbyist Coder Passionate About React Web Development
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="mailto:antti.murtsi@gmail.com" target="_blank" rel="noopener noreferrer">
              <AiFillMail />
            </a>
            <a href="https://www.linkedin.com/in/antti-murtokangas-562725158/" target="_blank" rel="noopener noreferrer">
              <AiFillLinkedin />
            </a>
                <a href="https://github.com/Murtsi" target="_blank" rel="noopener noreferrer">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-gray-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            </div>
          </div>
        </section>
        <section ref={offerRef} className={`transition-opacity duration-1000 ${offerInView ? 'opacity-100' : 'opacity-0'}`}>
          <div>
          <h3 className="text-5xl py-1 text-gray-900 dark:text-gray-100 font-bold">
              What I Can Offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
            I am a dedicated and passionate individual with a strong background in automation engineering and frontend web development. My skills include:

            - Proficiency in React and modern JavaScript frameworks
            - Experience with HTML, CSS, and responsive design
            - Knowledge of backend technologies and RESTful APIs
            - Strong problem-solving abilities and attention to detail
            - Excellent communication and teamwork skills

            I am eager to bring my expertise and enthusiasm to a dynamic team, where I can contribute to innovative projects and continue to grow as a developer.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-light-blue-500 dark:bg-gray-700 flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-900 dark:text-gray-100">
                My skills
              </h3>
              <p className="py-2 text-gray-900 dark:text-gray-100">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-900 dark:text-gray-100 py-1">Photoshop</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Illustrator</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Figma</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-light-blue-500 dark:bg-gray-700 flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-900 dark:text-gray-100">
                My technical background
              </h3>
              <p className="py-2 text-gray-900 dark:text-gray-100">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-900 dark:text-gray-100 py-1">Photoshop</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Illustrator</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Figma</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-light-blue-500 dark:bg-gray-700 flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-900 dark:text-gray-100">
                My personal traits
              </h3>
              <p className="py-2 text-gray-900 dark:text-gray-100">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-900 dark:text-gray-100 py-1">Photoshop</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Illustrator</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Figma</p>
              <p className="text-gray-900 dark:text-gray-100 py-1">Indesign</p>
            </div>
          </div>
        </section>
        <section ref={portfolioRef} className={`py-10 transition-opacity duration-1000 ${portfolioInView ? 'opacity-100' : 'opacity-0'}`}>
          <div>
            <div className="bg-white shadow-lg rounded-xl p-10 dark:bg-gray-800">
              <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Portofolio</h3>
              <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
              </p>
              <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                Further details on my skills and competencies
              </p>
              <section className="py-10">
                <div
                  ref={workRef}
                  className={`bg-light-blue-500 shadow-lg rounded-xl p-10 dark:bg-gray-700 transition-opacity duration-1000 ${workInView ? 'opacity-100' : 'opacity-0'}`}
                >
                  <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Work Experience</h3>
                  <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                    I have worked in the automation field and with technology, including IT support and other related areas, collaborating with talented individuals to implement efficient and innovative solutions.
                  </p>
                  <ul className="list-disc list-inside text-gray-900 dark:text-gray-100">
                    <li>Porting user interfaces to Codesys html5 ()</li>
                    <li>Production supervisor at Olvi ()</li>
                    <li>Production operator at Keitele timber()</li>
                    <li>It Support for local highschool for final work()</li>
                  </ul>
                </div>
                <div
                  ref={educationRef}
                  className={`mt-10 bg-light-blue-500 shadow-lg rounded-xl p-10 dark:bg-gray-700 transition-opacity duration-1000 ${educationInView ? 'opacity-100' : 'opacity-0'}`}
                >
                  <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Education</h3>
                  <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                    My education in Technology is comprehensive and well-rounded, providing me with a strong foundation in the field.
                  </p>
                  <ul className="list-disc list-inside text-gray-900 dark:text-gray-100">
                  <li>Course to Automation in the wind power sector (2024)</li>
                    <li>Bachelor's Degree in Automation Engineering, Seinäjoki University of Applied Sciences (2021 - Present)</li>
                    <li>Leadership Training/Military Police Officer  (2019-2020)</li>
                    <li>Vocational Qualification in Business Information Technology, Järviseutu Vocational Institute (2015-2018)</li>
                  </ul>
                </div>
                <div
                  ref={languageRef}
                  className={`mt-10 bg-light-blue-500 shadow-lg rounded-xl p-10 dark:bg-gray-700 transition-opacity duration-1000 ${languageInView ? 'opacity-100' : 'opacity-0'}`}
                >
                  <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Language Skills</h3>
                  <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                    I am proficient in multiple languages, which allows me to work with a diverse range of clients.
                  </p>
                  <ul className="list-disc list-inside text-gray-900 dark:text-gray-100">
                    <li>English (Fluent)</li>
                    <li>Finnish (Native)</li>
                    <li>Germany (Intermediate)</li>
                    <li>Estonian (Intermediate)</li>
                  </ul>
                </div>
              </section>
            </div>
          </div>
        </section>
      </main>

      <Modal
        isOpen={isModalOpen}
        onRequestClose={() => setIsModalOpen(false)}
        contentLabel="Resume Modal"
        className="modal"
        overlayClassName="overlay"
      >
        <button onClick={() => setIsModalOpen(false)} className="close-button">
          Close
        </button>
        <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.js">
          <Viewer fileUrl="/CV.pdf" />
        </Worker>
      </Modal>
      <style jsx global>{`
        .modal {
          position: absolute;
          top: 50%;
          left: 50%;
          right: auto;
          bottom: auto;
          margin-right: -50%;
          transform: translate(-50%, -50%);
          background: white;
          padding: 20px;
          border-radius: 10px;
          max-width: 90%;
          max-height: 90%;
          overflow: auto;
        }
        .overlay {
          background: rgba(0, 0, 0, 0.75);
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          z-index: 1000;
        }
        .close-button {
          background: #ff5f5f;
          color: white;
          border: none;
          padding: 10px;
          border-radius: 5px;
          cursor: pointer;
          position: absolute;
          top: 10px;
          right: 10px;
        }
      `}</style>
    </div>
  );
}