import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillMessage,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import code from "../public/code.png";
import design from "../public/automation.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useInView } from 'react-intersection-observer';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const { ref: workRef, inView: workInView } = useInView();
  const { ref: educationRef, inView: educationInView } = useInView();
  const { ref: languageRef, inView: languageInView } = useInView();
  const { ref: offerRef, inView: offerInView } = useInView();
  const { ref: portfolioRef, inView: portfolioInView } = useInView();

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Antti Murtokangas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">My Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Antti Murtokangas
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Student & Hobbyist frontend coder
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Automation Engineering Student & Hobbyist Coder Passionate About React Web Development
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="mailto:antti.murtsi@gmail.com" target="_blank" rel="noopener noreferrer">
              <AiFillMail />
            </a>
            <a href="https://www.linkedin.com/in/antti-murtokangas-562725158/" target="_blank" rel="noopener noreferrer">
              <AiFillLinkedin />
            </a>
                <a href="https://github.com/Murtsi" target="_blank" rel="noopener noreferrer">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-gray-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src="/omakuva.jpg" layout="fill" objectFit="cover" alt="Omakuva" />
            </div>
          </div>
        </section>
        <section ref={offerRef} className={`transition-opacity duration-1000 ${offerInView ? 'opacity-100' : 'opacity-0'}`}>
          <div>
          <h3 className="text-5xl py-1 text-gray-900 dark:text-gray-100 font-bold">
              What I Can Offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
            I am a dedicated and passionate individual with a strong background in automation engineering and hobbyist coding. My skills include:
            </p>
            <ul className="list-disc pl-5 text-md leading-8 text-gray-900 dark:text-gray-100">
              <li>Extensive experience in automation engineering, including PLC programming, SCADA systems, and industrial automation planning</li>
              <li>Basic understanding of React and modern JavaScript frameworks</li>
              <li>Experience with Python for scripting and automation tasks</li>
              <li>Knowledge of HTML, CSS, and responsive design</li>
              <li>Reading and writing of electrical circuit diagrams</li>
              <li>Strong problem-solving abilities and attention to detail</li>
              <li>Excellent communication and teamwork skills</li>
            </ul>
            <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
            I am eager to bring my expertise and enthusiasm to a dynamic team, where I can contribute to innovative projects and continue to grow.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-light-blue-500 dark:bg-gray-700 flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-900 dark:text-gray-100">
                Automation Engineering
              </h3>
              <p className="py-2 text-gray-900 dark:text-gray-100 font-semibold">
                Tools that I've used in my studies and work and have knowledge in:
              </p>
              <ul className="list-disc pl-5 text-gray-900 dark:text-gray-100">
                <li className="py-1">Codesys V3.5 Sp17 Patch 3</li>
                <li className="py-1">Eplan</li>
                <li className="py-1">Cognex in-sight Explorer</li>
                <li className="py-1">Visual components Premium</li>
              </ul>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-light-blue-500 dark:bg-gray-700 flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-900 dark:text-gray-100">
                My technical background
              </h3>
              <p className="py-2 text-gray-900 dark:text-gray-100 font-semibold">
                Additional tools in my technical field that I am proficient in
              </p>
              <ul className="list-disc pl-5 text-gray-900 dark:text-gray-100">
                <li className="py-1">Photoshop</li>
                <li className="py-1">Illustrator</li>
                <li className="py-1">Figma</li>
                <li className="py-1">Indesign</li>
              </ul>
            </div>
          </div>
        </section>
        <section ref={portfolioRef} className={`py-10 transition-opacity duration-1000 ${portfolioInView ? 'opacity-100' : 'opacity-0'}`}>
          <div>
            <div className="bg-white shadow-lg rounded-xl p-10 dark:bg-gray-800">
              <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Portofolio</h3>
              <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
              </p>
              <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                Further details on my skills and competencies
              </p>
              <section className="py-10">
                <div
                  ref={workRef}
                  className={`bg-light-blue-500 shadow-lg rounded-xl p-10 dark:bg-gray-700 transition-opacity duration-1000 ${workInView ? 'opacity-100' : 'opacity-0'}`}
                >
                  <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Work Experience</h3>
                  <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                    I have worked in the automation field and with technology, including IT support and other related areas, collaborating with talented individuals to implement efficient and innovative solutions.
                  </p>
                  <ul className="list-disc list-inside text-gray-900 dark:text-gray-100 space-y-4">
                    <li>Porting user interfaces to Codesys html5 ()</li>
                    <li>Production supervisor at Olvi ()</li>
                    <li>Production operator at Keitele timber()</li>
                    <li>It Support for local highschool for final work()</li>
                  </ul>
                </div>
                <div
                  ref={educationRef}
                  className={`mt-10 bg-light-blue-500 shadow-lg rounded-xl p-10 dark:bg-gray-700 transition-opacity duration-1000 ${educationInView ? 'opacity-100' : 'opacity-0'}`}
                >
                  <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Education</h3>
                  <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                    My education in Technology is comprehensive and well-rounded, providing me with a strong foundation in the field.
                  </p>
                  <ul className="list-disc list-inside text-gray-900 dark:text-gray-100 space-y-4">
                    <li>Course to Automation in the wind power sector (2024)</li>
                    <li>Bachelor's Degree in Automation Engineering, Seinäjoki University of Applied Sciences (2021 - Present)</li>
                    <li>Leadership Training/Military Police Officer  (2019-2020)</li>
                    <li>Vocational Qualification in Business Information Technology, Järviseutu Vocational Institute (2015-2018)</li>
                  </ul>
                </div>
                <div
                  ref={languageRef}
                  className={`mt-10 bg-light-blue-500 shadow-lg rounded-xl p-10 dark:bg-gray-700 transition-opacity duration-1000 ${languageInView ? 'opacity-100' : 'opacity-0'}`}
                >
                  <h3 className="text-3xl py-1 text-gray-900 dark:text-gray-100 font-bold">Language Skills</h3>
                  <p className="text-md py-2 leading-8 text-gray-900 dark:text-gray-100">
                    I am proficient in multiple languages, which allows me to work with a diverse range of clients.
                  </p>
                  <ul className="list-disc list-inside text-gray-900 dark:text-gray-100 space-y-4">
                    <li>English (Fluent)</li>
                    <li>Finnish (Native)</li>
                    <li>German (Intermediate)</li>
                    <li>Estonian (Intermediate)</li>
                  </ul>
                </div>
              </section>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
